### ISSUE TITLE
Update email address of test records

### ISSUE THREAD

**Issue by fitztrev** [lichess-org/lila-db-seed#29]
Test users get created with an email address in format `lichess.waste.basket+{username}@gmail.com`. When Lichess normalizes email addresses for certain operations, anything after the `+` is excluded. In the case of these test users, that's the identifying part.

After changing the format, you should be able to use the "sign in with link" functionality and lila should send an email to the test user's address.

**Comment by schlawg** [comment]
I'm not sure lila-db-seed is the right street here. There is a UI for that in dasher / Preferences / Change email.

**Comment by schlawg** [comment]
I mean someone could add a --email argument to spamdb.py and create all users with that address - but it wouldn't configure an smtp server for you.

**Comment by fitztrev** [comment]
Fair enough. I was testing the magic link login functionality and was trying to figure out why lila wasn't triggering emails for any of the test users, but it would if I manually created a separate user.

That's the approach I ended up taking--changing the user's email address via the UI.
