### ISSUE TITLE
Seed Practice page with sample Studies

### ISSUE THREAD

**Issue by M-DinhHoangViet** [lichess-org/lila-db-seed#34]
![image](https://github.com/lichess-org/lila-docker/assets/134517889/a810dbf2-42e1-4213-be3a-67b2b1fe6a2f)

**Comment by schlawg** [comment]
If someone wants to tackle this, note that by default - the config data is stored in the `_id:'practice'` document of the `flag` collection. It is just a string containing a [hocon configuration](https://github.com/lightbend/config/blob/master/HOCON.md#hocon-human-optimized-config-object-notation) (you may also use json as shown below). It looks like:
```
lichess> db.flag.find()
[
  {
    _id: 'practice',
    config:
      '"sections": [{ "name": "Openings", "id": "openings", "studies": [' +
      '  { "name": "Best Opening", "id": "xdfCCggd", "desc": "Best Opening" }' +
      ... +
      ']}]'
  }
]
```
There is also a web interface for playing with this configuration at http://localhost:9663/practice/config - only users with privileges (such as `admin`) can view this page.
